



apiVersion: v1
kind: Pod
metadata:
  name: startup-probe-pod
  labels:               
    app: busybox
spec: 
  containers:
  - name: busybox-container
    image: busybox
    command: ["/bin/sh","-c"]
    args:
      - sleep 20 && touch /tmp/started && sleep 3600
    startupProbe:
      exec:
        command:
          - cat
          - /tmp/started
      periodSeconds: 5
      failureThreshold: 12  
      initialDelaySeconds: 20
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/started
      periodSeconds: 5
      initialDelaySeconds: 20
      failureThreshold: 3


      