
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-labels
  labels:
    app: postgres
    environment: development
    team: devops-team
spec:
  containers:
  - name: postgres-container
    image: postgres:alpine
    env:
    - name:  POSTGRES_PASSWORD
      value: "password"

