apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: demo
  hostPath:
    path: /tmp/data1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: demo
  hostPath:
    path: /tmp/data2

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-3
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: demo
  hostPath:
    path: /tmp/data3
--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-4
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: demo
  hostPath:
    path: /tmp/data4
--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-5
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: demo
  hostPath:
    path: /tmp/data5
