apiVersion: v1
kind: Pod
metadata:
  name: pvc-claim-pod
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - |
          date > /data/message.txt;
          sleep 3600
      volumeMounts:
        - name: pv-volume
          mountPath: /data
      
  volumes:
  - name: pv-volume
    persistentVolumeClaim:
      claimName: pvc

  


