

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Defines what happens to the data (PV) after the PVC is deleted.
  hostPath:
    path: /tmp/k8s-pv-data
  storageClassName: manual


