apiVersion: v1
kind: Pod
metadata:
  name: task6-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c", "echo Hello > /data/file.txt && sleep 3600"]
    volumeMounts:
    - name: storage
      mountPath: /data

  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: pvc-task6