services:
  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress-db
    ports:
      - "80:80"
    networks:
      - wordpress-networks
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wordpress-networks
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
  wordpress:

networks:
  wordpress-networks: